/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package approximateprefix

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"iter"
	"unsafe"

	"github.com/cespare/xxhash/v2"
	"sigs.k8s.io/controller-runtime/pkg/log"

	logutil "github.com/llm-d/llm-d-router/pkg/common/observability/logging"
	fwkrh "github.com/llm-d/llm-d-router/pkg/epp/framework/interface/requesthandling"
	"github.com/llm-d/llm-d-router/pkg/epp/framework/interface/scheduling"
)

// HashBlock wraps prompt or tokenized prompt which is later used for calculating prefix hashes.
type HashBlock struct {
	// PseudoTokens represents estimated tokens derived directly from raw prompt.
	// It is used when the EPP only has access to raw prompts and actual tokenization hasn't occurred.
	PseudoTokens []byte
	// Tokens represents the exact, definitive token IDs generated by the tokenizer.
	// It is used when the input has been fully processed into actual tokens.
	Tokens []uint32
}

// Hash computes a stable unique identifier for the HashBlock content.
// Since a block represents either estimated tokens (PseudoTokens) or exact tokens (Tokens),
// we return early once the active content is hashed.
func (b HashBlock) Hash() uint64 {
	if len(b.PseudoTokens) > 0 {
		return xxhash.Sum64(b.PseudoTokens)
	}

	if len(b.Tokens) > 0 {
		byteSlice := unsafe.Slice((*byte)(unsafe.Pointer(&b.Tokens[0])), len(b.Tokens)*4)
		return xxhash.Sum64(byteSlice)
	}

	return 0
}

// getBlockHashes divides the prompt into blocks and calculates a prefix cache hash for each block.
// The first block hash includes the model name and cache salt (if provided).
// For subsequent blocks, the hash is calculated as: hash(block i content, hash(i-1)).
func getBlockHashes(ctx context.Context, request *scheduling.InferenceRequest, blockSizeTokens int, maxPrefixBlocks int, tokenEstimator TokenEstimator) []blockHash {
	loggerDebug := log.FromContext(ctx).V(logutil.DEBUG)
	if request == nil || request.Body == nil {
		loggerDebug.Info("Request or request data is nil, skipping hashing")
		return nil
	}

	seq, err := getKVCacheBlocksFromRawPrompt(ctx, request, blockSizeTokens, tokenEstimator)
	if err != nil {
		loggerDebug.Error(err, "Failed to get kv cache blocks")
		return nil
	}

	blockHashes := computeBlockHashes(seq, request, maxPrefixBlocks)
	if len(blockHashes) == 0 {
		loggerDebug.Info("No kv cache block found")
		return nil
	}

	return blockHashes
}

// computeBlockHashes calculates the hash for content blocks.
func computeBlockHashes(seq iter.Seq[HashBlock], request *scheduling.InferenceRequest, maxPrefixBlocks int) []blockHash {
	var blockHashes []blockHash

	h := xxhash.New()
	// Different models should have different hashes even with the same body.
	_, _ = h.Write([]byte(request.TargetModel))
	if cacheSalt := request.Body.CacheSalt(); cacheSalt != "" {
		_, _ = h.Write([]byte(cacheSalt))
	}

	prevBlockHash := blockHash(h.Sum64())

	count := 0
	for block := range seq {
		if count >= maxPrefixBlocks {
			break
		}
		h.Reset()
		blockID := block.Hash()
		_, _ = h.Write(toBytes(blockHash(blockID)))
		_, _ = h.Write(toBytes(prevBlockHash))
		blockHashes = append(blockHashes, blockHash(h.Sum64()))

		prevBlockHash = blockHashes[len(blockHashes)-1]
		count++
	}

	return blockHashes
}

func toBytes(i blockHash) []byte {
	bytes := make([]byte, 8)
	binary.LittleEndian.PutUint64(bytes, uint64(i))
	return bytes
}

func getKVCacheBlocksFromRawPrompt(ctx context.Context, request *scheduling.InferenceRequest, blockSizeTokens int, tokenEstimator TokenEstimator) (iter.Seq[HashBlock], error) {
	switch {
	case request.Body.Conversations != nil:
		rawBytes, err := json.Marshal(request.Body.Conversations.Items)
		if err != nil {
			return nil, errors.New("failed to marshal conversations")
		}
		return getKVCacheBlocksFromRawBytes(rawBytes, blockSizeTokens), nil
	case request.Body.Responses != nil:
		var combined []map[string]interface{}
		if request.Body.Responses.Instructions != nil {
			combined = append(combined, map[string]interface{}{"instructions": request.Body.Responses.Instructions})
		}
		if request.Body.Responses.Tools != nil {
			combined = append(combined, map[string]interface{}{"tools": request.Body.Responses.Tools})
		}
		combined = append(combined, map[string]interface{}{"input": request.Body.Responses.Input})
		rawBytes, err := json.Marshal(combined)
		if err != nil {
			return nil, errors.New("failed to marshal responses")
		}
		return getKVCacheBlocksFromRawBytes(rawBytes, blockSizeTokens), nil

	case request.Body.Messages != nil:
		var combined []map[string]interface{}
		if sysText := request.Body.Messages.System.PlainText(); sysText != "" {
			combined = append(combined, map[string]interface{}{"system": sysText})
		}
		if request.Body.Messages.Tools != nil {
			combined = append(combined, map[string]interface{}{"tools": request.Body.Messages.Tools})
		}
		combined = append(combined, map[string]interface{}{"messages": request.Body.Messages.Messages})
		rawBytes, err := json.Marshal(combined)
		if err != nil {
			return nil, errors.New("failed to marshal messages")
		}
		return getKVCacheBlocksFromRawBytes(rawBytes, blockSizeTokens), nil

	case request.Body.ChatCompletions != nil:
		return getKVCacheBlocksFromChatCompletions(ctx, request, blockSizeTokens, tokenEstimator), nil

	case request.Body.Completions != nil:
		rawBytes := []byte(request.Body.Completions.Prompt.PlainText())
		return getKVCacheBlocksFromRawBytes(rawBytes, blockSizeTokens), nil

	case request.Body.Generate != nil:
		return getKVCacheBlocksFromTokens(request.Body.Generate.TokenIDs, blockSizeTokens), nil

	case request.Body.Embeddings != nil:
		rawBytes, err := json.Marshal(request.Body.Embeddings.Input)
		if err != nil {
			return nil, errors.New("failed to marshal embeddings")
		}
		return getKVCacheBlocksFromRawBytes(rawBytes, blockSizeTokens), nil

	default:
		return nil, errors.New("invalid request body: no recognized API format found")
	}
}

func getKVCacheBlocksFromTokens(ids []uint32, blockSizeTokens int) iter.Seq[HashBlock] {
	return func(yield func(HashBlock) bool) {
		if len(ids) == 0 || blockSizeTokens <= 0 {
			return
		}
		for i := 0; i < len(ids); i += blockSizeTokens {
			end := i + blockSizeTokens
			if end > len(ids) {
				end = len(ids)
			}
			if !yield(HashBlock{Tokens: ids[i:end]}) {
				return
			}
		}
	}
}

func getKVCacheBlocksFromRawBytes(rawBytes []byte, blockSizeTokens int) iter.Seq[HashBlock] {
	return func(yield func(HashBlock) bool) {
		if len(rawBytes) == 0 {
			return
		}

		blockSizeBytes := blockSizeTokens * averageCharactersPerToken

		for i := 0; i < len(rawBytes); i += blockSizeBytes {
			blockEnd := i + blockSizeBytes
			if blockEnd > len(rawBytes) {
				blockEnd = len(rawBytes)
			}

			block := HashBlock{
				PseudoTokens: rawBytes[i:blockEnd],
			}
			if !yield(block) {
				return
			}
		}
	}
}

func getKVCacheBlocksFromChatCompletions(ctx context.Context, request *scheduling.InferenceRequest, blockSizeTokens int, tokenEstimator TokenEstimator) iter.Seq[HashBlock] {
	loggerDebug := log.FromContext(ctx).V(logutil.DEBUG)
	messages := request.Body.ChatCompletions.Messages
	var allPseudoBytes []byte

	for _, msg := range messages {
		if msg.Role != "" {
			allPseudoBytes = append(allPseudoBytes, []byte(msg.Role)...)
		}
		if msg.Content.Raw != "" {
			allPseudoBytes = append(allPseudoBytes, []byte(msg.Content.Raw)...)
		} else if len(msg.Content.Structured) > 0 {
			for _, block := range msg.Content.Structured {
				switch block.Type {
				case "text":
					allPseudoBytes = append(allPseudoBytes, []byte(block.Text)...)
				case "image_url":
					// multimodal content can't be in the same pseudo token of text.
					allPseudoBytes = padToAlignment(allPseudoBytes, averageCharactersPerToken)
					url := block.ImageURL.URL
					numPlaceHolders := tokenEstimator.Estimate(fwkrh.ContentBlock{
						Type:     "image_url",
						ImageURL: fwkrh.ImageBlock{URL: url},
					})

					imgHashVal := xxhash.Sum64([]byte(url))
					imgHashBytes := make([]byte, 4)
					binary.LittleEndian.PutUint32(imgHashBytes, uint32(imgHashVal))
					for i := 0; i < numPlaceHolders; i++ {
						allPseudoBytes = append(allPseudoBytes, imgHashBytes...)
					}
				case "video_url":
					// Add video support later
					// multimodal content can't be in the same pseudo token of text.
					allPseudoBytes = padToAlignment(allPseudoBytes, averageCharactersPerToken)
					allPseudoBytes = append(allPseudoBytes, []byte(block.VideoURL.URL)...)
				case "input_audio", "audio_url":
					// Add audio support later
					// multimodal content can't be in the same pseudo token of text.
					allPseudoBytes = padToAlignment(allPseudoBytes, averageCharactersPerToken)
					allPseudoBytes = append(allPseudoBytes, []byte(block.InputAudio.Data)...)
					allPseudoBytes = append(allPseudoBytes, []byte(block.InputAudio.Format)...)
				default:
					loggerDebug.Info("Unsupported block type: " + block.Type)

				}
			}
		}
	}

	return getKVCacheBlocksFromRawBytes(allPseudoBytes, blockSizeTokens)
}

func padToAlignment(b []byte, alignment int) []byte {
	remainder := len(b) % alignment
	if remainder == 0 {
		return b
	}
	padding := alignment - remainder
	for i := 0; i < padding; i++ {
		b = append(b, 0)
	}
	return b
}
