apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${POOL_NAME}-sidecar-ssrf
  namespace: ${NAMESPACE}
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "inference.networking.k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${POOL_NAME}-sidecar-ssrf
  namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${POOL_NAME}-sidecar-ssrf
