apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${POOL_NAME}-sidecar-ssrf
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "inference.networking.k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${POOL_NAME}-sidecar-ssrf
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${POOL_NAME}-sidecar-ssrf
